name: workspace
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^3.2.7
  stacked_services: ^1.0.2
  get_it : ^8.0.3
  maps_toolkit: ^3.1.0
  dio: ^5.1.2
  intl: ^0.20.2
  dropdown_textfield : ^1.0.8
  shared_preferences: ^2.4.4
  location: ^8.0.0
  network_info_plus: ^6.1.3
  local_session_timeout: ^3.2.0
  animated_splash_screen: ^1.3.0
  flutter_slidable: ^4.0.0
  table_calendar: ^3.0.9
  carousel_slider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  stacked_generator:
  retrofit_generator:
  flutter_native_splash:
  flutter_launcher_icons: ^0.14.3
  pretty_dio_logger: ^1.2.0-beta-1


flutter:

  uses-material-design: true


  fonts:
   - family: Poppins-Light
     fonts:
       - asset: assets/fonts/Poppins-Light.ttf
   - family: Poppins-Medium
     fonts:
       - asset: assets/fonts/Poppins-Medium.ttf    
   - family: Poppins-Regular
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf   
   - family: Poppins-SemiBold
     fonts:
       - asset: assets/fonts/Poppins-SemiBold.ttf

  assets:
   - assets/images/
   - assets/icons/
