name: workspace
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^3.2.7
  stacked_services: ^1.0.2
  get_it : ^7.6.0
  dropdown_textfield : ^1.0.8
  maps_toolkit: ^2.0.1
  dio: ^5.1.2
  shared_preferences: ^2.1.1
  geolocator: ^9.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  stacked_generator:
  retrofit_generator:
  flutter_native_splash:
  flutter_launcher_icons: ^0.9.2
  pretty_dio_logger: ^1.2.0-beta-1


flutter:

  uses-material-design: true


fonts:
  - family: times new roman
    fonts:
      - asset: assets/fonts/times new roman.ttf
  - family: times new roman bold
    fonts:
      - asset: assets/fonts/times new roman bold.ttf    
  - family: times new roman italic
    fonts:
      - asset: assets/fonts/times new roman italic.ttf
