name: workspace
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^3.2.7
  stacked_services: ^1.0.2
  get_it : ^7.6.0
  dropdown_textfield : ^1.0.8
  maps_toolkit: ^2.0.1
  dio: ^5.1.2
  shared_preferences: ^2.0.13
  location: ^4.4.0
  network_info_plus: ^4.0.1
  local_session_timeout: ^2.3.0
  animated_splash_screen: ^1.3.0
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  date_picker_timeline: ^1.2.5
  table_calendar: ^3.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  stacked_generator:
  retrofit_generator:
  flutter_native_splash:
  flutter_launcher_icons: ^0.9.2
  pretty_dio_logger: ^1.2.0-beta-1


flutter:

  uses-material-design: true


  fonts:
   - family: Poppins-Light
     fonts:
       - asset: assets/fonts/Poppins-Light.ttf
   - family: Poppins-Medium
     fonts:
       - asset: assets/fonts/Poppins-Medium.ttf    
   - family: Poppins-Regular
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf   
   - family: Poppins-SemiBold
     fonts:
       - asset: assets/fonts/Poppins-SemiBold.ttf

  assets:
   - assets/images/
   - assets/icons/
